### ISSUE TITLE
2 heavy

### ISSUE THREAD

**Issue by Sese92** [LuisHPorras/la-travesia-de-los-caracoles#1]
Please, don´t upload `node_modules` folder.

**Comment by baumannzone** [comment]
Learn to ignore folders

**Comment by LuisHPorras** [comment]
Contentos? <3

**Comment by baumannzone** [comment]
No, where the hell is the fking `.gitignore` file?

**Comment by LuisHPorras** [comment]
Si claro, encima quieres que te enseñe yo a ti a ignorar archivos

**Comment by baumannzone** [comment]
CLOSE if u are done, PLEASE
